# base directory (by default, everything will be installed here)
# base_dir = "/path/to/base/milieux/dir"

# directory for virtual environments
# env_dir = "envs"

# [pip]
# URL for default PyPI index
# default_index_url = "https://pypi.org/simple"
# URLs for extra indexes, in descending priority order (but all taking priority over the default)
# index_urls = ["https://internal-pypi-mirror.example.com"]
