# base directory (by default, everything will be installed here)
# base_dir = "/path/to/base/milieux/dir"

# directory for virtual environments
# env_dir = "envs"

# [pip]
# URL for PyPI index
# default_index_url = "https://pypi.org/simple"
# index_urls = ["https://internal-pypi-mirror.example.com"]
